// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5msIYqmfMRayI3dbYuAlS2Yy0g8mqJs',
    appId: '1:1029488636413:web:aeaabe38d1654044a3e994',
    messagingSenderId: '1029488636413',
    projectId: 'flutter-dev-test-74c7a',
    authDomain: 'flutter-dev-test-74c7a.firebaseapp.com',
    databaseURL: 'https://flutter-dev-test-74c7a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-dev-test-74c7a.firebasestorage.app',
    measurementId: 'G-ET25YV2RN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBogKS1dyZM2YgUxPImWIQF5-RnuICWU78',
    appId: '1:1029488636413:android:6bc865eb107af632a3e994',
    messagingSenderId: '1029488636413',
    projectId: 'flutter-dev-test-74c7a',
    databaseURL: 'https://flutter-dev-test-74c7a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-dev-test-74c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqu4vBUPIk9onKSiPFa6Y1SklnM1TTWGY',
    appId: '1:1029488636413:ios:9e675b6b33f4bd2ea3e994',
    messagingSenderId: '1029488636413',
    projectId: 'flutter-dev-test-74c7a',
    databaseURL: 'https://flutter-dev-test-74c7a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-dev-test-74c7a.firebasestorage.app',
    iosBundleId: 'com.example.noteTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqu4vBUPIk9onKSiPFa6Y1SklnM1TTWGY',
    appId: '1:1029488636413:ios:9e675b6b33f4bd2ea3e994',
    messagingSenderId: '1029488636413',
    projectId: 'flutter-dev-test-74c7a',
    databaseURL: 'https://flutter-dev-test-74c7a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-dev-test-74c7a.firebasestorage.app',
    iosBundleId: 'com.example.noteTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP5msIYqmfMRayI3dbYuAlS2Yy0g8mqJs',
    appId: '1:1029488636413:web:c9ac7cf40a122601a3e994',
    messagingSenderId: '1029488636413',
    projectId: 'flutter-dev-test-74c7a',
    authDomain: 'flutter-dev-test-74c7a.firebaseapp.com',
    databaseURL: 'https://flutter-dev-test-74c7a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-dev-test-74c7a.firebasestorage.app',
    measurementId: 'G-7XHXXW7M48',
  );
}
